name: Cypress E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch: # Allows manual trigger

jobs:
  # Simple smoke test job for quick feedback
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npx cypress install --force

      - name: Verify setup
        run: |
          npx cypress verify
          npx cypress info
          echo "Node: $(node --version)"
          echo "NPM: $(npm --version)"
          echo "Files:"
          ls -la cypress/e2e/ || echo "No e2e folder found"

      - name: Run smoke tests
        run: |
          npx cypress run \
            --browser chrome \
            --headless \
            --env grepTags="@smoke" \
            --spec "cypress/e2e/**/*.cy.js"
        env:
          CYPRESS_baseUrl: https://demowebshop.tricentis.com

      - name: Upload smoke test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: smoke-test-results
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 7

  # Main test job - Chrome browser
  cypress-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npx cypress install --force

      - name: Run all tests - Chrome
        run: |
          npx cypress run \
            --browser chrome \
            --headless \
            --spec "cypress/e2e/**/*.cy.js"
        env:
          CYPRESS_baseUrl: https://demowebshop.tricentis.com
          CYPRESS_viewportWidth: 1280
          CYPRESS_viewportHeight: 720

      - name: Upload Chrome test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: chrome-test-results
          path: |
            cypress/screenshots
            cypress/videos
            cypress/reports
          retention-days: 30

  # Test report generation
  generate-report:
    runs-on: ubuntu-latest
    needs: [smoke-tests, cypress-chrome]
    if: always()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Generate test summary
        run: |
          mkdir -p reports
          echo "# Cypress Test Results" > reports/README.md
          echo "" >> reports/README.md
          echo "## Test Run Summary" >> reports/README.md
          echo "- **Timestamp**: $(date)" >> reports/README.md
          echo "- **Branch**: ${{ github.ref_name }}" >> reports/README.md
          echo "- **Commit**: ${{ github.sha }}" >> reports/README.md
          echo "- **Workflow**: ${{ github.run_number }}" >> reports/README.md
          echo "" >> reports/README.md
          
          # Count artifacts
          if [ -d "artifacts/" ]; then
            echo "### Artifacts Generated:" >> reports/README.md
            find artifacts/ -name "*.mp4" | wc -l | xargs echo "- Videos:" >> reports/README.md
            find artifacts/ -name "*.png" | wc -l | xargs echo "- Screenshots:" >> reports/README.md
            echo "" >> reports/README.md
            echo "### Artifact Structure:" >> reports/README.md
            ls -la artifacts/ >> reports/README.md
          else
            echo "- No artifacts directory found" >> reports/README.md
          fi

      - name: Upload consolidated report
        uses: actions/upload-artifact@v4
        with:
          name: test-summary-report
          path: reports/
          retention-days: 90