name: Cypress E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    strategy:
      # Run tests in parallel across multiple browsers
      matrix:
        browser: [chrome, edge, firefox]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Cypress binary
        run: npx cypress install

      - name: Verify Cypress
        run: npx cypress verify

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          headless: true
          record: false
          config-file: cypress.config.js
          spec: |
            cypress/e2e/**/*.cy.js
        env:
          CYPRESS_baseUrl: https://demowebshop.tricentis.com
          # Add any environment variables your tests need
          CYPRESS_viewportWidth: 1280
          CYPRESS_viewportHeight: 720

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots
          retention-days: 30

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos
          retention-days: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-results-${{ matrix.browser }}
          path: |
            cypress/results
            cypress/reports
          retention-days: 30

  # Separate job for smoke tests that runs faster
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run smoke tests only
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
          spec: cypress/e2e/**/*.cy.js
          config: |
            {
              "env": {
                "grepTags": "@smoke"
              }
            }
        env:
          CYPRESS_baseUrl: https://demowebshop.tricentis.com

      - name: Upload smoke test artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: smoke-test-artifacts
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 7

  # Job for generating test reports
  generate-report:
    runs-on: ubuntu-latest
    needs: [cypress-run, smoke-tests]
    if: always()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Install report dependencies
        run: |
          npm install --save-dev mochawesome mochawesome-merge mochawesome-report-generator

      - name: Generate consolidated report
        run: |
          mkdir -p reports
          echo "# Cypress Test Results" > reports/summary.md
          echo "" >> reports/summary.md
          echo "## Test Run Summary" >> reports/summary.md
          echo "- **Timestamp**: $(date)" >> reports/summary.md
          echo "- **Branch**: ${{ github.ref_name }}" >> reports/summary.md
          echo "- **Commit**: ${{ github.sha }}" >> reports/summary.md
          echo "" >> reports/summary.md
          
          # Count artifacts to estimate test results
          SCREENSHOT_COUNT=$(find . -name "cypress-screenshots-*" -type d | wc -l)
          VIDEO_COUNT=$(find . -name "cypress-videos-*" -type d | wc -l)
          
          echo "- **Browsers Tested**: chrome, edge, firefox" >> reports/summary.md
          echo "- **Screenshot Artifacts**: $SCREENSHOT_COUNT" >> reports/summary.md
          echo "- **Video Artifacts**: $VIDEO_COUNT" >> reports/summary.md

      - name: Upload consolidated report
        uses: actions/upload-artifact@v4
        with:
          name: test-report-summary
          path: reports/
          retention-days: 90