name: Debug CI Setup

on:
  workflow_dispatch: # Manual trigger only

jobs:
  debug-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Debug environment
        run: |
          echo "=== ENVIRONMENT DEBUG ==="
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Working directory: $(pwd)"
          echo ""
          echo "=== FILE STRUCTURE ==="
          ls -la
          echo ""
          echo "=== PACKAGE.JSON EXISTS? ==="
          ls -la package.json || echo "No package.json found"
          echo ""
          echo "=== CYPRESS FOLDER ==="
          ls -la cypress/ || echo "No cypress folder"
          echo ""
          echo "=== E2E TESTS ==="
          find . -name "*.cy.js" -type f || echo "No .cy.js files found"

      - name: Try npm install
        run: |
          echo "=== INSTALLING DEPENDENCIES ==="
          if [ -f package.json ]; then
            npm ci
            echo "Dependencies installed successfully"
          else
            echo "No package.json found - cannot install dependencies"
            exit 1
          fi

      - name: Try Cypress install
        run: |
          echo "=== INSTALLING CYPRESS BINARY ==="
          npx cypress install --force
          echo "=== VERIFYING CYPRESS ==="
          npx cypress verify
          echo "=== CYPRESS INFO ==="
          npx cypress info

      - name: List Cypress files
        run: |
          echo "=== CYPRESS STRUCTURE ==="
          if [ -d cypress ]; then
            find cypress -type f -name "*.js" | head -20
            echo ""
            echo "=== TEST FILES ==="
            find cypress/e2e -name "*.cy.js" | head -10 || echo "No test files found"
          else
            echo "No cypress directory found"
          fi

      - name: Test environment variables
        run: |
          echo "=== ENVIRONMENT VARIABLES DEBUG ==="
          echo "CYPRESS_BASE_URL: ${CYPRESS_BASE_URL:-'NOT SET'}"
          echo "CYPRESS_VIEWPORT_WIDTH: ${CYPRESS_VIEWPORT_WIDTH:-'NOT SET'}"
          echo "CYPRESS_VIEWPORT_HEIGHT: ${CYPRESS_VIEWPORT_HEIGHT:-'NOT SET'}"
          echo "CYPRESS_DEFAULT_COMMAND_TIMEOUT: ${CYPRESS_DEFAULT_COMMAND_TIMEOUT:-'NOT SET'}"
          echo "CYPRESS_TEST_USER_EMAIL: ${CYPRESS_TEST_USER_EMAIL:-'NOT SET'}"
          echo "CYPRESS_TEST_USER_PASSWORD: ${CYPRESS_TEST_USER_PASSWORD:-'NOT SET (HIDDEN)'}"
          echo "CYPRESS_BROWSER: ${CYPRESS_BROWSER:-'NOT SET'}"
          echo "CYPRESS_HEADLESS: ${CYPRESS_HEADLESS:-'NOT SET'}"
          echo "CYPRESS_VIDEO: ${CYPRESS_VIDEO:-'NOT SET'}"
          echo "CYPRESS_SCREENSHOTS: ${CYPRESS_SCREENSHOTS:-'NOT SET'}"
        env:
          # Map GitHub secrets/variables to test environment access
          CYPRESS_BASE_URL: ${{ vars.CYPRESS_BASE_URL || 'https://demowebshop.tricentis.com' }}
          CYPRESS_VIEWPORT_WIDTH: ${{ vars.CYPRESS_VIEWPORT_WIDTH || '1280' }}
          CYPRESS_VIEWPORT_HEIGHT: ${{ vars.CYPRESS_VIEWPORT_HEIGHT || '720' }}
          CYPRESS_DEFAULT_COMMAND_TIMEOUT: ${{ vars.CYPRESS_DEFAULT_COMMAND_TIMEOUT || '10000' }}
          CYPRESS_REQUEST_TIMEOUT: ${{ vars.CYPRESS_REQUEST_TIMEOUT || '10000' }}
          CYPRESS_RESPONSE_TIMEOUT: ${{ vars.CYPRESS_RESPONSE_TIMEOUT || '10000' }}
          CYPRESS_BROWSER: ${{ vars.CYPRESS_BROWSER || 'chrome' }}
          CYPRESS_HEADLESS: ${{ vars.CYPRESS_HEADLESS || 'true' }}
          CYPRESS_VIDEO: ${{ vars.CYPRESS_VIDEO || 'true' }}
          CYPRESS_SCREENSHOTS: ${{ vars.CYPRESS_SCREENSHOTS || 'true' }}
          CYPRESS_REPORTER: ${{ vars.CYPRESS_REPORTER || 'cypress-mochawesome-reporter' }}
          CYPRESS_TEST_USER_EMAIL: ${{ secrets.CYPRESS_TEST_USER_EMAIL || 'test@example.com' }}
          CYPRESS_TEST_USER_PASSWORD: ${{ secrets.CYPRESS_TEST_USER_PASSWORD || 'Test123!' }}

      - name: Test simple Cypress command
        run: |
          echo "=== TESTING CYPRESS VERSION ==="
          npx cypress --version
          echo "=== TESTING CYPRESS RUN (DRY RUN) ==="
          npx cypress run --help | head -20
        env:
          # Include environment variables for Cypress commands
          CYPRESS_BASE_URL: ${{ vars.CYPRESS_BASE_URL || 'https://demowebshop.tricentis.com' }}
          CYPRESS_VIEWPORT_WIDTH: ${{ vars.CYPRESS_VIEWPORT_WIDTH || '1280' }}
          CYPRESS_VIEWPORT_HEIGHT: ${{ vars.CYPRESS_VIEWPORT_HEIGHT || '720' }}

      - name: Setup virtual display for browser testing
        run: |
          echo "=== SETTING UP VIRTUAL DISPLAY ==="
          sudo apt-get update
          sudo apt-get install -y xvfb google-chrome-stable
          export DISPLAY=:99
          Xvfb :99 -screen 0 1280x720x24 > /dev/null 2>&1 &
          sleep 2
          echo "✓ Virtual display setup complete"

      - name: Test browser launch
        run: |
          echo "=== TESTING BROWSER LAUNCH ==="
          google-chrome --version
          echo "Testing headless Chrome launch..."
          google-chrome --headless --disable-gpu --no-sandbox --disable-dev-shm-usage --version || echo "Chrome headless failed"
        env:
          DISPLAY: ':99'

      - name: Test actual test run
        run: |
          echo "=== ATTEMPTING SINGLE TEST RUN ==="
          npx cypress run \
            --browser chrome \
            --headless \
            --spec "cypress/e2e/99-basic-test.cy.js" \
            --no-exit || echo "Test run failed - check logs above"
        env:
          # Full environment for actual test with forced headless
          CYPRESS_BASE_URL: ${{ vars.CYPRESS_BASE_URL || 'https://demowebshop.tricentis.com' }}
          CYPRESS_VIEWPORT_WIDTH: ${{ vars.CYPRESS_VIEWPORT_WIDTH || '1280' }}
          CYPRESS_VIEWPORT_HEIGHT: ${{ vars.CYPRESS_VIEWPORT_HEIGHT || '720' }}
          CYPRESS_DEFAULT_COMMAND_TIMEOUT: ${{ vars.CYPRESS_DEFAULT_COMMAND_TIMEOUT || '10000' }}
          CYPRESS_REQUEST_TIMEOUT: ${{ vars.CYPRESS_REQUEST_TIMEOUT || '10000' }}
          CYPRESS_RESPONSE_TIMEOUT: ${{ vars.CYPRESS_RESPONSE_TIMEOUT || '10000' }}
          CYPRESS_BROWSER: ${{ vars.CYPRESS_BROWSER || 'chrome' }}
          CYPRESS_HEADLESS: true  # Force headless in debug too
          CYPRESS_VIDEO: ${{ vars.CYPRESS_VIDEO || 'true' }}
          CYPRESS_SCREENSHOTS: ${{ vars.CYPRESS_SCREENSHOTS || 'true' }}
          CYPRESS_REPORTER: ${{ vars.CYPRESS_REPORTER || 'cypress-mochawesome-reporter' }}
          CYPRESS_TEST_USER_EMAIL: ${{ secrets.CYPRESS_TEST_USER_EMAIL || 'test@example.com' }}
          CYPRESS_TEST_USER_PASSWORD: ${{ secrets.CYPRESS_TEST_USER_PASSWORD || 'Test123!' }}
          DISPLAY: ':99'
          CI: true